"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getParser = exports.HTMLTypeset = exports.testList = exports.treeStats = exports.printerTransform = exports.Printer = exports.htmlVoidTagMap = exports.elementSnabbdom = exports.elementDom = exports.elementDefault = exports.treeRender = exports.TreeMatcher = exports.TreeBuilder = exports.XMLParser = void 0;
var treeRender = require("./treerender");
exports.treeRender = treeRender;
var treebuilder_1 = require("./treebuilder");
exports.TreeBuilder = treebuilder_1.default;
var treematcher_1 = require("./treematcher");
exports.TreeMatcher = treematcher_1.default;
var printer_1 = require("./printer");
exports.Printer = printer_1.default;
var default_1 = require("./element/default");
exports.elementDefault = default_1.default;
var dom_1 = require("./element/dom");
exports.elementDom = dom_1.default;
var snabbdom_1 = require("./element/snabbdom");
exports.elementSnabbdom = snabbdom_1.default;
var htmlvoidtagmap_1 = require("./htmlvoidtagmap");
exports.htmlVoidTagMap = htmlvoidtagmap_1.default;
var printerTransform = require("./printertransform");
exports.printerTransform = printerTransform;
treebuilder_1.default.optDefault.element = default_1.default;
treebuilder_1.default.optDefault.tagVoidMap = htmlvoidtagmap_1.default;
printer_1.default.optDefault.tagVoidMap = htmlvoidtagmap_1.default;
var xmlparser_1 = require("./xmlparser");
Object.defineProperty(exports, "XMLParser", { enumerable: true, get: function () { return xmlparser_1.default; } });
var treestats_1 = require("./treestats");
Object.defineProperty(exports, "treeStats", { enumerable: true, get: function () { return treestats_1.default; } });
var testlist_1 = require("./testlist");
Object.defineProperty(exports, "testList", { enumerable: true, get: function () { return testlist_1.default; } });
var htmltypeset_1 = require("./htmltypeset");
Object.defineProperty(exports, "HTMLTypeset", { enumerable: true, get: function () { return htmltypeset_1.default; } });
var getparser_1 = require("./getparser");
Object.defineProperty(exports, "getParser", { enumerable: true, get: function () { return getparser_1.default; } });
